<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evilmasterbase" nsURI="http://www.example.org/evilmasterbase"
    nsPrefix="evilmasterbase">
  <eClassifiers xsi:type="ecore:EClass" name="Repere">
    <eStructuralFeatures xsi:type="ecore:EReference" name="salle" upperBound="-1"
        eType="#//Salle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bureau" lowerBound="1"
        eType="#//Bureau" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="couloir" upperBound="-1"
        eType="#//Couloir" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Salle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="piege" upperBound="-1"
        eType="#//Piege" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sbire" upperBound="-1"
        eType="#//Sbire" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sbire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bureau" eSuperTypes="#//Salle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Couloir" eSuperTypes="#//Salle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="salle" lowerBound="2" upperBound="2"
        eType="#//Salle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Piege"/>
</ecore:EPackage>
