<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evilmasterbase" nsURI="http://www.lpdql.org/evilmasterbase"
    nsPrefix="evilmasterbase">
  <eClassifiers xsi:type="ecore:EClass" name="Repere" eSuperTypes="#//DescribedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="porte" upperBound="-1"
        eType="#//Porte" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localisation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salle" upperBound="-1"
        eType="#//Salle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Salle" eSuperTypes="#//DescribedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="escouade" upperBound="-1"
        eType="#//Escouade" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="piege" upperBound="-1"
        eType="#//Piege" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Escouade" eSuperTypes="#//PricedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bureau" eSuperTypes="#//Salle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Porte" eSuperTypes="#//PricedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="salle1" lowerBound="1"
        eType="#//Salle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salle2" lowerBound="1"
        eType="#//Salle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Piege" eSuperTypes="#//PricedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dangerosité" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entree" eSuperTypes="#//Salle"/>
  <eClassifiers xsi:type="ecore:EClass" name="PricedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true" interface="true"
      eSuperTypes="#//PricedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Couloir" eSuperTypes="#//Salle"/>
</ecore:EPackage>
